### PR TITLE
Feature/function getter

### LINKED ISSUE #40: Write C++ functions and read in as text string
Should be able to write a C++ function in a separate file, then read that file in as a character string, rather than defining the function as a string. Would be much more convenient.

### PR DESCRIPTION
**Pull request by pwinskill**
Adds functionality to scrape a tagged .cpp file to extract a drJacoby compatible string (for the log likelihood or log prior function).

Closes #40 

Borrows a similar approach to that in MalariaFit work, but brings it internal to the package which is more appropriate.

### CODE REVIEW

**Review by bobverity — CHANGES_REQUESTED** [review]
This all looks fantastic, but can we merge into develop rather than master? I think this should be one of the many changes that we make for version 1.1.0

**Comment by pwinskill** [comment]
Ok, have switched to develop @bobverity. I think this build was failing before this PR, don't have time to dive into it now, but will take a look at some point.

**Comment by bobverity** [comment]
Cool cool. I guess I'll leave this as a pull request for now until we have it merging with no conflicts.

**Comment by pwinskill** [comment]
Sure. When we get time lets have a chat about the other changes in develop (its the cpp::check on y example likelihoods failing and I see there are changes to the format of likelihood functions)

**Comment by pwinskill** [comment]
Just looking at this old PR request @bobverity. Do you agree that this functionality would still be useful? If so I can clean up properly

**Comment by bobverity** [comment]
Yes, 100%! Hopefully there aren't so many changes in between last PR that it's a huge pain now.

**Comment by pwinskill** [comment]
Ok great I'll do this at some point then.

**Pull request closed without merging**
